/*--------------------------------------------------------------*/
/* 1. Example macro variables passed from a previous flow step   */
/*    In practice, these could be generated by model training    */
/*    or parsed from a JSON file in an earlier program.          */
/*--------------------------------------------------------------*/
%let run_date = %sysfunc(datetime(), datetime19.);
%let model_name = Manufacturing Alert Model;
%let flow_name  = Model Retraining Flow;
%let push_status = SUCCESS;
%let commit_id   = abc123def456;
%let commit_msg  = Automated update after model retraining;

/* Variable importance values */
%let vi_1_name = Dust_feed;
%let vi_1_abs  = 1946055;
%let vi_1_rel  = 1.0000;

%let vi_2_name = Differential_pressure;
%let vi_2_abs  = 1447021;
%let vi_2_rel  = 0.7436;

%let vi_3_name = Time;
%let vi_3_abs  = 53641;
%let vi_3_rel  = 0.0276;

%let vi_4_name = Dust;
%let vi_4_abs  = 50212;
%let vi_4_rel  = 0.0258;

%let vi_5_name = Flow_rate;
%let vi_5_abs  = 35143;
%let vi_5_rel  = 0.0181;

/*--------------------------------------------------------------*/
/* 2. SMTP configuration                                         */
/*    Use placeholders for paper/repository examples             */
/*--------------------------------------------------------------*/
options emailsys=smtp
        emailhost="mailhost.example.com"
        emailport=25;

filename alertmail email
   to=("analytics-team@example.com")
   from="sas-flow@example.com"
   subject="Model Retraining Alert: Updated Variable Importance";

/*--------------------------------------------------------------*/
/* 3. Send email                                                 */
/*--------------------------------------------------------------*/
data _null_;
  file alertmail;

  put "Hello Team,";
  put;
  put "This is an automated alert from a SAS flow.";
  put "The model retraining process completed and the repository was updated.";
  put;
  put "Flow Details";
  put "------------";
  put "Flow Name    : &flow_name.";
  put "Model Name   : &model_name.";
  put "Run Time     : &run_date.";
  put "Push Status  : &push_status.";
  put "Commit ID    : &commit_id.";
  put "Commit Msg   : &commit_msg.";
  put;
  put "Updated Variable Importance";
  put "---------------------------";
  put "Variable                  Importance      Relative Importance";
  put "------------------------------------------------------------";
  put "&vi_1_name.                  &vi_1_abs.          &vi_1_rel.";
  put "&vi_2_name.     &vi_2_abs.          &vi_2_rel.";
  put "&vi_3_name.                       &vi_3_abs.            &vi_3_rel.";
  put "&vi_4_name.                       &vi_4_abs.            &vi_4_rel.";
  put "&vi_5_name.                  &vi_5_abs.            &vi_5_rel.";
  put;
  put "This message was sent automatically from SAS.";
  put;
  put "Regards,";
  put "SAS Flow Automation";
run;